# Generated by Django 5.1.3 on 2024-11-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=10)),
                ("dob", models.DateField(verbose_name="dateOfBirth")),
                ("first_name", models.CharField(max_length=15)),
                ("last_name", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Uniform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[("White", "White"), ("Black", "Black")], max_length=10
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Polo", "Polo"), ("Pants", "Pants")], max_length=10
                    ),
                ),
            ],
        ),
    ]
