# Generated by Django 5.1.3 on 2024-11-12 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uniform_req_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniformRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Fulfilled", "Fulfilled")],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uniform_req_app.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UniformRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="uniform_req_app.uniformrequest",
                    ),
                ),
                (
                    "uniform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uniform_req_app.uniform",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeUniform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uniform_req_app.employee",
                    ),
                ),
                (
                    "uniform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uniform_req_app.uniform",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "uniform"), name="unique_employee_uniform"
                    )
                ],
            },
        ),
    ]
