# Generated by Django 5.1.3 on 2024-11-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uniform_req_app", "0002_uniformrequest_uniformrequestitem_employeeuniform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uniform",
            name="color",
        ),
        migrations.AlterField(
            model_name="uniform",
            name="type",
            field=models.CharField(
                choices=[("White Polo", "White Polo"), ("Black Pants", "Black Pants")],
                max_length=20,
                unique=True,
            ),
        ),
    ]
